StanfordUniversity/ViewModels/CoursesViewModel.cs
using StanfordUniversity.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StanfordUniversity.ViewModels
{
    public class CoursesViewModel
    {
        public int CourseID { get; set; }
        public String Name { get; set; }
        public String Description { get; set; }
        public virtual ICollection<GroupsViewModel> Groups { get; set; }

    }
}

StanfordUniversity/Controllers/CoursesController.cs
using StanfordUniversity.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Xunit;

namespace StanfordUniversity.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CourcesService _servCource;

        public CoursesController(CourcesService servCource)
        {
            _servCource = servCource;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _servCource.GetIndexAsync());
        }

        // GET: Courses/Details/5
        public IActionResult Details(int? id)
        {


            //var srv = new Mock<CourcesService>();
            //var coursesController = new CoursesController(_servCource);
            //var actionResult = coursesController.Index();
            //var viewResult = Assert.IsType<ViewResult>(actionResult);
            //Assert.IsAssignableFrom<Courses>(viewResult.ViewData.Model);



            if (id == null)
            {
                return NotFound();
            }

            var courses = _servCource.GetDetails(id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CourseID,Name,Description")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                _servCource.Create(courses);
                return RedirectToAction(nameof(Index));
            }
            return View(courses);
        }

        // GET: Courses/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courses = _servCource.Edit(id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("CourseID,Name,Description")] Courses courses)
        {
            if (id != courses.CourseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var coursesResult = _servCource.Edit(courses);
                if (coursesResult == null)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }

            return View(courses);
        }
    }
}

StanfordUniversity/Controllers/GroupsController.cs
using StanfordUniversity.Models;
using StanfordUniversity.Services;
using StanfordUniversity.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace StanfordUniversity.Controllers
{
    public class GroupsController : Controller
    {
        private readonly GroupsService _servGroups;

        public GroupsController(GroupsService servGroups)
        {
            _servGroups = servGroups;
        }

        // GET: Groups
        public IActionResult Index()
        {
            return View(_servGroups.GetIndex());
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var groups = await _servGroups.GetDetailsAsync(id);
            if (groups == null)
                return NotFound();

            return View(groups);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Group_ID,Course_ID,Name")] Groups groups)
        {
            if (ModelState.IsValid)
            {
                await _servGroups.CreateAsync(groups);
                return RedirectToAction(nameof(Index));
            }
            return View(groups);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> EditAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groups = await _servGroups.EditAsync(id);
            if (groups == null)
            {
                return NotFound();
            }
            return View(groups);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAsync(int id, Groups groups)
        {
            if (id != groups.GroupID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var groupsResult = await _servGroups.EditAsync(groups);
                if (groupsResult == null)
                    return NotFound();

                return RedirectToAction(nameof(Index));
            }
            return View(groups);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var groups = await _servGroups.DeleteAsync(id);
            if (groups == null)
                return NotFound();

            return View(groups);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var groups = await _servGroups.DeleteConfirmedAsync(id);
            if (groups != null)
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. This group is not empty. Transfer students to a different group  " +
                    "and try again.";

                return View(groups);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

StanfordUniversity/Views/Courses/Create.cshtml
@model StanfordUniversity.ViewModels.CoursesViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Courses</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CourseID" class="control-label"></label>
                <input asp-for="CourseID" class="form-control" />
                <span asp-validation-for="CourseID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StanfordUniversity/Views/Courses/Details.cshtml
@model StanfordUniversity.ViewModels.CoursesViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Courses</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Group Title</th>
                    <th>Student list</th>
                </tr>
                @foreach (var item in Model.Groups)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @*<a asp-controller="Groups" asp-action="Details/@item.GroupID" asp-route-area="">Student list</a>*@

                            <a asp-controller="Groups" asp-action="Details" asp-route-id=@item.GroupID>Student list</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

StanfordUniversity/Views/Courses/Edit.cshtml
@model StanfordUniversity.ViewModels.CoursesViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Courses</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CourseID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StanfordUniversity/Views/Courses/Index.cshtml
@model IEnumerable<StanfordUniversity.ViewModels.CoursesViewModel>

@{
    ViewData["Title"] = "Our courses";
}

<h1>Our courses</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CourseID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CourseID">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>